apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: CHANGEME
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: CHANGEME
  filterTags:
    pattern: '^main-(?P<num>[0-9]+)$'
    extract: '$num'
  policy:
    numerical:
      order: asc
