apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - source.yaml
  - ghcr-app.yaml
components:
  - ../../templates/image-automation
patches:
  - target:
      kind: ImageRepository
    patch: |
      - op: replace
        path: /metadata/name
        value: ghcr-app
      - op: replace
        path: /spec/image
        value: ghcr.io/ppbrown/ghcr-test
  - target:
      kind: ImagePolicy
    patch: |
      - op: replace
        path: /metadata/name
        value: ghcr-app
      - op: replace
        path: /spec/imageRepositoryRef/name
        value: ghcr-app
