---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fluxcd-ghcr-app
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/ppbrown/fluxcd-ghcr-app
  ref:
    branch: main
